spring:
  application:
    name: trading-game-backend
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5777/trading
    username: trading
    password: trading

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: trading
        show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: trading
    liquibase-schema: trading

jwt:
  secret: OFnuJBYJC04pOZA0URQL69j4GZQywbGYm7PXAigbD7c=
  expiration: 86400000

cors:
  allowed-origins: http://localhost:4200

logging: 
  level: 
    org:
      springframework: 
        security: DEBUG
        web: DEBUG
